Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: cinecriticpal-predict-rating:latest
      Environment:
        Variables:
          MODEL_PATH: model/
      EphemeralStorage:
        Size: 512
      Events:
        PredictAPI:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: POST

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage for the API Gateway deployment
